trigger:
  - main

variables:
  - group: 'bluegreen-poc-variables'
  - name: vmImageName
    value: 'ubuntu-latest'
  - name: containerRegistry
    value: 'containerRegistryConnection'
  - name: imageRepository 
    value: 'weatherapi'
  - name: tag
    value: $(Build.BuildId)
  - name: resourceGroupName 
    value: 'bluegreen-poc-rg'
  - name: appName 
    value: 'velidacontainerwebapp'

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: '$(containerRegistry)'
              repository: '$(imageRepository)'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(tag)
          
          - task: AzureWebAppContainer@1
            displayName: 'Azure Web App on Container Deploy'
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(appName)
              containers: $(containerRegistry)/$(imageRepository):$(tag)
              deployToSlotOrASE: true
              resourceGroupName: $(resourceGroupName)
              slotName: blue

          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: $(azureSubscription)
              WebAppName: $(appName)
              ResourceGroupName: $(resourceGroupName)
              SourceSlot: blue
              SwapWithProduction: true

  - stage: ManualValidation
    dependsOn: Build 
    jobs:
      - job: WaitForValidation
        displayName: 'Validate Blue Slot'
        pool: server
        timeoutInMinutes: 4320
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 1440
            inputs:
              notifyUsers: |
                willvelida@hotmail.co.uk
                willvelida@microsoft.com
              instructions: 'Please validate blue slot before switching to green'
              onTimeout: 'reject'
  
  - stage: DeployToGreen
    dependsOn: ManualValidation
    jobs:
      - job: Deploy
        displayName: Deploy to Green Slot
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: $(azureSubscription)
              WebAppName: $(appName)
              ResourceGroupName: $(resourceGroupName)
              SourceSlot: blue
              SwapWithProduction: true
