trigger:
  - main

variables:
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'containerRegistryConnection'
              repository: 'weatherapi'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'